version: '3.8'

services:
  HYAPI:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - TARGET_BUILDER=${TARGET_BUILDER}
      - TEST_USERS=${TEST_USERS}
  